Feature 47 add manager domain
classvar/classvar-user-backend pull request #48
Opened 2021-11-05 08:30 UTC by arsgsg1

closed #47

2021-11-06 10:35 UTC, Devconf approved these changes

2021-11-08 04:28 UTC, seongbin9786 requested changes

2021-11-08 04:38 UTC, arsgsg1 commented on src/main/java/com/classvar/manager/application/ManagerQueryProcessor.java
> +        .map(o -> {
우선 감독관과 유저의 엔티티가 간접 참조 관계이기 때문에, 하나의 엔티티로 결과를 받아올 수 없어서 List<Object[]>의 형태로 받았고, 이 방법 외에도 다른 방법이 있는데 여기를 참조하시면 더 자세하게 알 수 있습니다.
[쿼리 프로젝션](https://velog.io/@neity16/5-%EC%8A%A4%ED%94%84%EB%A7%81-%EB%8D%B0%EC%9D%B4%ED%84%B0-JPA-10-%EB%82%98%EB%A8%B8%EC%A7%80-%EA%B8%B0%EB%8A%A5%EB%93%A4Projections-Native-Query-%EB%93%B1)
대표적인게 별도의 DTO를 만들어서 받아오는 방법인데, 이렇게 할 경우 infra 영역에 의존이 생겨서 지양했습니다.
그 외에 조회를 아예 두 번하는 경우도 있는데 join으로 한 번에 가져올 수 있는걸 굳이 쿼리를 두 번 날리는건 낭비라고 생각했습니다.

2021-11-08 04:54 UTC, arsgsg1 commented on src/main/java/com/classvar/manager/application/ManagerQueryProcessor.java
> +        .map(o -> {
제가 장점 부분에 대해선 어필을 딱히 안했는데, 쿼리가 복잡하지 않기 때문에 별도의 인터페이스 코드를 추가하지 않고 캐스팅으로 깔끔하게 해결하는게 베스트라 생각했습니다.
만약 복잡해질 경우엔 다른 방법을 쓰는게 나을텐데, 이 경우 프로젝션보단 querydsl 같은 조회용 프레임워크를 사용하는게 더 나을거라 생각되네용

2021-11-08 05:05 UTC, seongbin9786 commented on src/main/java/com/classvar/manager/application/ManagerQueryProcessor.java
> +        .map(o -> {
생각해보니, User와 join을 하는 듯한데 이 부분에 대해선 나중에 회의에서 얘기해보면 좋을 것 같습니다.

2021-11-08 05:05 UTC, merged

2021-11-08 05:12 UTC, Devconf commented on src/main/java/com/classvar/manager/application/ManagerQueryProcessor.java
> +        .map(o -> {
우선 manager create 할때 email list로 받아오는거 아니였나요? email, managerId를 dto로 받아오지 않는거 같습니다.