Feature 46 add login fail
classvar/classvar-user-backend pull request #49
Opened 2021-11-05 10:31 UTC by enrouteeee

close #46

2021-11-06 10:34 UTC, Devconf approved these changes

2021-11-06 11:03 UTC, arsgsg1 approved these changes

2021-11-08 04:29 UTC, seongbin9786 requested changes

2021-11-08 04:33 UTC, Devconf commented on src/main/java/com/classvar/user/controller/UserCommandController.java
> +    // 로그인 실패
그러게요

2021-11-08 04:40 UTC, enrouteeee commented on src/main/java/com/classvar/user/controller/UserCommandController.java
> +    // 로그인 실패
~~~
  @PostMapping(value = "/signup")
  public ResponseEntity userSignUp(@Valid @RequestBody CreateOrUpdateUserDto dto) {
    userCommandExecutor.createUser(dto);
    return ResponseEntity.status(HttpStatus.OK).build();
  }

  @PostMapping(value = "/login")
  public ResponseEntity login(@Valid @RequestBody LoginDto dto, HttpServletRequest request) {

    Long loginId = userCommandExecutor.login(dto);

    // 로그인 실패
    if (loginId == null) {
      throw new IllegalArgumentException("아이디 비밀번호가 일치하지 않습니다.");
    }

    HttpSession session = request.getSession();
    session.setAttribute(SessionConst.
            LOGIN_ID, loginId);
    return ResponseEntity.status(HttpStatus.OK).build();
  }
~~~

이 상태로 작업되어 있는데 혹시 다르게 보이시나요?

2021-11-08 04:42 UTC, Devconf commented on src/main/java/com/classvar/user/controller/UserCommandController.java
> +    // 로그인 실패
push 안하신거 같아요

2021-11-08 04:45 UTC, enrouteeee commented on src/main/java/com/classvar/user/controller/UserCommandController.java
> +    // 로그인 실패
push 안돼있나요..?
https://github.com/classvar/classvar-user-backend/blob/feature-46-add-login-fail/src/main/java/com/classvar/user/controller/UserCommandController.java
제가 저거 복사를 여기서 해온건데 여기 반영된건 안된 상태인가요??

2021-11-08 05:10 UTC, seongbin9786 commented on src/main/java/com/classvar/user/controller/UserCommandController.java
> +    // 로그인 실패
일단 올려주신 링크의 내용만 보면 문제가 없는데, 저 링크와 다른 내용이 이 pr에 올라와있는 건지 조금 더 봐야 할 것 같습니다

2021-11-08 05:11 UTC, seongbin9786 commented on src/main/java/com/classvar/user/controller/UserCommandController.java
> +    // 로그인 실패
아래 보시면, 

```
Conflicting files
src/main/java/com/classvar/common/config/WebConfig.java
src/main/java/com/classvar/common/interceptor/LoginCheckInterceptor.java
src/main/java/com/classvar/user/controller/UserCommandController.java
```
라고 나와있는데 이 부분의 conflict가 있어서 수정을 manual하게 하시고 추가 push를 진행하시면 될 것 같습니다. @enrouteeee

2021-11-08 08:51 UTC, seongbin9786 approved these changes

2021-11-08 08:51 UTC, merged